#
# Module manifest for module 'PureStorageDbaTools'
#
# Generated by: Chris Adkin
#
# Generated on: 05/07/2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PureStorageDbaTools.psm1'

# Version number of this module.
ModuleVersion = '1.7.3.1'

# ID used to uniquely identify this module
GUID = '190c8acb-d09f-4e24-99a6-5bb968373904'

# Author of this module
Author = 'cadkin@purestorage.com'

# Company or vendor of this module
CompanyName = 'Pure Storage'

# Copyright statement for this module
Copyright = '(c) 2018 Pure Storage. All rights reserved. Available under the Apache 2.0 license'

# Description of the functionality provided by this module
Description = 'Tools for refreshing SQL Server databases via FlashArray crash consistent snapshots'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('PureStoragePowerShellSDK', 'dbatools')

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @('New-PfaDbSnapshot', 'Invoke-PfaDbRefresh', 'Enable-DataMasks')

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}
